{% set version="0.5.2b" %}
about:
  home: https://github.com/luntergroup/octopus
  license: MIT
  summary: Bayesian haplotype-based mutation calling
package:
  name: octopus
  version: {{ version }}
build:
  number: 0
  # Not building on osx CircleCI and unsure how to fix; does not pick
  # up 7.2 compilers
  skip: true # [osx]
source:
  url: https://github.com/luntergroup/octopus/archive/v0.5.2-beta.tar.gz
  sha256: 080e8946a3171769567c0b541b1c964b19148d4545f1c6767838b856a2804a05 
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - libboost
    - htslib
    - wget
    - icu
    - bzip2
    - xz
    - zlib
  run:
    - libboost
    - htslib
    - icu
    - bzip2
    - xz
    - zlib
test:
  commands:
    - octopus -h
