{% set version = "0.99.11" %}
{% set name = "DIAlignR" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 2b16b2621dbdd7aebfaaa18102ca6b4f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: BiocStyle, knitr, GEOquery, stringr
requirements:
  host:
    - 'r-zoo >= 1.8-3'
    - 'bioconductor-mzr >=2.18.0'
    - r-base
    - r-boot
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-signal
    - r-scales
    - r-gridextra
    - r-rsqlite
    - r-dbi
    - r-rcpp
  run:
    - 'r-zoo >= 1.8-3'
    - 'bioconductor-mzr >=2.18.0'
    - r-base
    - r-boot
    - r-ggplot2
    - r-dplyr
    - r-tidyr
    - r-signal
    - r-scales
    - r-gridextra
    - r-rsqlite
    - r-dbi
    - r-rcpp
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-3
  summary: 'MS2 chromatograms based alignment of targeted mass-spectrometry runs'
  description: 'R/Bioconductor package for MS2 chromatograms based alignment of targeted mass-spectrometry runs'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:dialignr
    - doi:10.1074/mcp.TIR118.001132
  parent_recipe:
    name: bioconductor-dialignr
    path: recipes/bioconductor-dialignr
    version: 1.0.0
