
package:
  name: cgat-daisy
  version: 0.1.1

source:
  url: https://files.pythonhosted.org/packages/cf/d1/fdc2188c74508d33cf55f107af057e1fc782e3a4b46a5ea66c531dbb26a7/cgat-daisy-0.1.1.tar.gz
  sha256: 1f86078c3d7ead18b3392db7561be5495e964e188785b696a13f8ad1145c88dc

build:
  noarch: python
  number: 0

requirements:
  host:
    - docutils
    - future
    - pytest
    - six
    - sphinx
    - python
    - pep8

  run:
    - cgatcore
    - pandas
    - sqlalchemy
    - ruffus
    - ruamel_yaml
    - pysam

test:
  commands:
    - daisy run --help

about:
  home: https://github.com/cgat-developers/cgat-daisy
  license: MIT
  license_file: LICENSE
  summary: "A system to design and execute benchmarks"
