package:
    name: 'r-shinybs'
    version: '0.25.0'
source: 
    url:
      - 'https://github.com/likelet/shinyBS/archive/v0.25.0.tar.gz'
    sha256: 5ec863bbbca3831094c81e552262730544e9efb0426c01b5caa4b51b539b005e
build:
    number: 0
    rpaths:
      - lib/R/lib/
      - lib/
requirements:
    build: 
      - {{ compiler('c') }}
    host:
      - r-base
      - 'r-shiny >= 0.8.0'
    run:
      - r-base 
      - 'r-shiny >= 0.8.0'
test:
    commands:
      - '$R -e "library(shinyBS)"'
about:
    date: '2014-03-13'
    summary:  'Twitter Bootstrap Components for Shiny'
    home: 'https://github.com/ebailey78/shinyBS'
    license: 'GPL-3'
